<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Botswana</name>
   <tag></tag>
   <elementGuidId>287a7afc-a47d-48a7-9c8c-7135a5fafdfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='iti-0__item-bw']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iti-0__item-bw > span.iti__country-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f65ddf94-46db-4556-87b2-502b86a425e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country-name</value>
      <webElementGuid>b1320f39-9817-4ec0-8f2b-30b6512d4ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Botswana</value>
      <webElementGuid>5cdc046e-795f-4f3e-823c-28328873a787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-0__item-bw&quot;)/span[@class=&quot;iti__country-name&quot;]</value>
      <webElementGuid>19b31f3f-e440-41f6-b6d5-be5bb5584444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='iti-0__item-bw']/span</value>
      <webElementGuid>e8a337ad-7a76-4d69-b308-4350e694fe2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bosnia and Herzegovina'])[1]/following::span[2]</value>
      <webElementGuid>b64012a4-4aa8-4c56-8de9-951b1d38915a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bolivia'])[1]/following::span[4]</value>
      <webElementGuid>cf42aba7-dc48-4435-a934-bd3d677c9f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brazil'])[1]/preceding::span[2]</value>
      <webElementGuid>5607d9f5-1b3e-46ae-8f9b-fc12c3f42a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='British Indian Ocean Territory'])[1]/preceding::span[4]</value>
      <webElementGuid>806bd51b-54ed-474f-838f-9c381d3d7a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Botswana']/parent::*</value>
      <webElementGuid>a0403809-8fee-435a-83a6-3b358dd1c932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[30]/span</value>
      <webElementGuid>620869fc-923d-4f8b-a6e2-4022bb231806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Botswana' or . = 'Botswana')]</value>
      <webElementGuid>ba5c2c36-3fb0-4a0f-ae1f-f2b9ec389c05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
