<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Your Message_Comment</name>
   <tag></tag>
   <elementGuidId>33048c75-73ed-4b2d-a419-cd41dfb28704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Form_submitForm_Comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Form_submitForm_Comment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>26a3f6cf-fd8d-4350-8ddf-cf540d548e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>90e7fd61-471a-49df-b0c2-579b51cf14a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>30487697-2ae1-4e51-8c62-9da9eaaf3c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Form_submitForm_Comment</value>
      <webElementGuid>071b25e2-604d-409c-8e5b-ddd8786d7d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5d926306-c4c3-48f9-acf9-eb42410fa001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>720a5da0-25a3-4631-b6ae-a506b6bd2383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your Message</value>
      <webElementGuid>c0c7047e-6044-418b-a095-753a7fe98e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4df142a2-66ac-4aed-acbe-ae622c07bc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4ff41b8d-16b0-4d76-9873-32fbed2e41a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a603943b-7bbb-4055-8f6f-4fbae4c109d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Form_submitForm_Comment&quot;)</value>
      <webElementGuid>5ec6e43b-3ab7-462c-bea0-972c69b0d52a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Form_submitForm_Comment']</value>
      <webElementGuid>0497f843-a444-470d-9789-962443c1146f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Form_submitForm_Comment_Holder']/div/textarea</value>
      <webElementGuid>ac2939ab-aba1-47ad-8f90-95b9f80b5a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1169dfed-8288-42bb-a45c-7f88c9ee0082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Comment' and @id = 'Form_submitForm_Comment' and @placeholder = 'Your Message']</value>
      <webElementGuid>248ba4a3-52cb-4a95-a3b0-62ee5f620679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
